### ISSUE TITLE
Images Not Downloading

### ISSUE THREAD

**Issue by MiraMinx** [SuperGouge/ChanThreadWatch#80] opened 2018-03-19 05:00 UTC
Just got the program and haven't been able to get it to download any images.  The HTML files download and the archiver recognizes how many images/files there are in a thread that it needs to download but it never gets past  0 completed and then after a bit just decides to cycle back to the timer until the next check.

**Comment by SuperGouge** [comment] 2018-03-19 09:51
On what site are you encountering this problem? Is it happening on a specific thread?
Also, can you upload the log file? On Windows, it should be found at `%AppData%\Chan Thread Watch\log.txt`.

**Comment by MiraMinx** [comment] 2018-03-19 16:46
4chan, any thread any board.  I've been looking at the log file every time
I open it but it's always blank.  Does that mean something?

**Comment by SuperGouge** [comment] 2018-03-19 18:45
This should mean there is no unexpected error. It seems to work on my end, though.
Could you try using another network connection or try saving the threads on a different folder/disk?

**Comment by MiraMinx** [comment] 2018-03-20 02:53
Switching drive they are downloading to did nothing, switching from a wired connection to a wireless did nothing, running .exe as administrator did nothing. :(

**Comment by DerSandmann-Badcode** [comment] 2018-03-20 07:02
It shouldn't matter, but could you give a bit more information on the system you're running it on?

Install Location, Operating system, and if you can find the settings file, that would be of some use as well.

Can you also include a screenshot of the UI? There's another version of CTW (The licence was updated recently) and I want to make sure you're running this one.

**Comment by MiraMinx** [comment] 2018-03-20 21:27
Installed on C drive in the Downloads folder, Windows 10, Settings file attached, screenshot attached.
[settings.txt](https://github.com/SuperGouge/ChanThreadWatch/files/1831264/settings.txt)
![2018-03-20](https://user-images.githubusercontent.com/37527182/37683731-93a52e36-2c5b-11e8-9213-2a62debcb478.png)

**Comment by MiraMinx** [comment] 2018-03-20 21:46
BTW I think its fine for right now but I think it also is a recurring problem.  I'm using CTW now to replace Ychan which has become unreliable for me, but I think CTW is suffering the same problem as it is on my computer.  I'm uncertain what's causing it.  Okay to give a full explanation as best as I can, CTW is now functioning on my PC as is Ychan at this time.  BUT when CTW was giving me the problem I had described earlier yesterday and the day before so was Ychan.  What happens in Ychan is that I put a thread URL in it or already have some in there from the last time I had launched the program (with it functioning right) and those threads get deleted probably from it pinging the URL and not getting any response I suppose and then deleting them as if they had 404'd as per design but mistakenly of course since the threads very much still exist.  But now that's confusing enough as it is since it will work for a few days and then not work for a few days.  But what makes things even more confusing is if something really is blocking the ability for these apps to see the threads why did I not get a return on the CTW saying doesn't exist (I know that's not what it says but you know what I mean) like I did on a thread just now that really did 404 and how come the CTW was able to download a copy of the html file? Oh and that does actually work, just no thumbnails and images along with it

**Comment by SuperGouge** [comment] 2018-03-20 22:06
A 404'd file should be skipped and removed from the total of images to download, so if all images are 404'd you should see the counter going down (e.g. `0 of 100` to `0 of 99`, etc.).
Are you behind a proxy or on a public network maybe (university, etc.)?

**Comment by DerSandmann-Badcode** [comment] 2018-03-21 00:18
Hey, by your screenshot, you're using the old version of CTW. Can you grab our Exe and give it another go?

**Comment by MiraMinx** [comment] 2018-03-21 06:53
No.  Home private network.

**Comment by DerSandmann-Badcode** [comment] 2018-03-21 07:07
Can you confirm the application is listed as 'Full Control' in the Security settings? There were some changes in some of these recent Windows 10 updates around application security.

![image](https://user-images.githubusercontent.com/8218786/37697680-107de6f4-2d43-11e8-903b-f4c27d300f85.png)

**Comment by beebz0** [comment] 2018-05-01 23:28
Adding on to here rather than making a new issue because it is the same issue.  CTW 1.16 can download from every site besides 4chan at current.  It will recognize that there are images in the thread and grab the html file, but it does not start the downloads.  In fact if I try to close CTW now it hangs as it cannot cancel one of the 4chan threads it is trying to download from and I need to kill it with task manager to close it.  Running on Windows 10 Ultimate on a home network.  No VPN's or whatnot

**Comment by beebz0** [comment] 2018-05-02 06:55
and now something else odd: I took a look at it and it no longer said it was no longer had the "Downloading images" status and was in the waiting period.  Stop and restarting it put it back into the stalled "Downloading images" status.  The log.txt is empty.

**Comment by SuperGouge** [comment] 2018-05-02 12:59
Working fine for me with CTW 1.16.0 on Windows 7 SP1 and Windows 10 Fall Creators Update.
If you still have problems with this site, can you try accessing the images from your browser and see if it works?

It seems like 4chan was having some intermittent issues with their image server last month, this could also be linked to the issues we see arising here.

**Comment by beebz0** [comment] 2018-05-02 17:47
Images load if I try to open them in a browser.  And my setup has nothing too special outside of ipv6 support.  Which is funny because I just tried to wget the image directly.  It failed 5 or 6 times trying to connect to an ipv6 address and then eventually passed when it tried the ipv4 address.  Trying to dso that to other sites, it immediately attempts to connect to an ipv4 address and works.  Could this be what's happening with CTW? If so, is it possible to force it to use ipv4?  I don't see anything in the settings

**Comment by beebz0** [comment] 2018-05-02 18:03
yeah, as soon as I disable ipv4 support for my network, CTW works perfectly fine

**Comment by DerSandmann-Badcode** [comment] 2018-05-03 03:04
I'll take a look. Thanks for digging a bit deeper into this.

**Comment by jwshields** [comment] 2018-12-09 06:14
Any movement on this? Disabling IPV6 isn't really a feasible solution.

I tried digging into the code, I assume it's to do with the DNS lookup or something with `WebRequest` but it didn't seem as if there was any option to force 4 or 6

**Comment by jwshields** [comment] 2018-12-09 06:42
I cleared my settings, blacklist, and log, tried with 1.16 and 1.7 - I was able to get the HTML to download once (no images though), but not any other times (tried with about ~10 threads)
I'm on Win10 1803, have a dual stack network (behind nat) with no outbound restrictions and nothing locally (AV/firewall) blocking the program

**Comment by DerSandmann-Badcode** [comment] 2018-12-19 00:34
@jwshields It's an issue with DNS lookups. I'm pretty sure this was resolved in later versions of the .Net framework. 

I can't test it myself, New Zealand isn't using Ipv6 yet. Are you able to grab the latest from the Git and change the .Net version to see if the problem still exists? If not, I could create a branch with that changed and create a release on it.

**Comment by jwshields** [comment] 2018-12-19 07:47
I was able to build it on my machine, but it seems 4chan is down at the moment. Will report back once it's back up and I can test.

Another note: I tested (the released build, not mine) 1.17.0 on a Win10 machine with ipv4 only, and had similar issues of the html not downloading & no images.

**Comment by jwshields** [comment] 2018-12-19 15:48
Looks like that fixed it for me.

**Comment by DerSandmann-Badcode** [comment] 2018-12-21 02:18
Thanks for confirming this, I was pretty confident .Net 2.0 has some bugs around DNS lookups. I'll see if there's a workaround for it besides using a newer version.

**Comment by jwshields** [comment] 2018-12-21 02:32
I tried poking around the docs but couldn't find much of anything. But this also isn't a language I'm fluent in. 
Any idea about the downloading vs not with debug vs release?

**Comment by jwshields** [comment] 2018-12-30 03:02
Hmm.
Have there been any changes in the settings.txt file recently? (1.15 and up)
I just re-built the solution with the `Release` config set, and was unable to repro the issue from earlier of debug working & release not.
But I had to completely wipe the directory (log, settings, blacklist, threads) - seems like it's working though.

To answer your questions though, my DNS and network are fully functional, dual stack, with nothing that is limiting how things resolve;

**Comment by DerSandmann-Badcode** [comment] 2018-12-31 10:21
@jwshields Yep, I'm able to reproduce it on my end.

This _might_ been broken since the stream throttling was added; When the 'first' download occurs, in the following code block, frmChanThreadWatch.ConcurrentDownloads (How many threads are downloading) is set to 0 and when we attempt to split the bandwidth between the current downloads we get a divide by 0 error. The error is then getting swallowed up the stack, so no error gets logged anywhere.

https://github.com/SuperGouge/ChanThreadWatch/blob/c02fbfe997f607a1031f7922bac607d6fd955016/Classes/Other.cs#L733-L757

**Comment by jwshields** [comment] 2018-12-31 23:56
Very nice find!

**Closed** 2019-01-13 14:53 UTC
Labels: bug
